### ISSUE TITLE
Not sure if this is a map or balance table issue

### ISSUE THREAD

**Issue by pdbossman** [vankruptgames/BalancingTable#3]
I'm getting a lot of errors that certain weapons are not in the zombie balance table.  This is on Vehicle Test Map (Rudy Random), in zombie mode.

LogDataTable: Warning: UDataTable::FindRow : '' requested row 'ar9' not in DataTable '/Game/ZombieMode/ZombieBalance_Table.ZombieBalance_Table'.

**Comment by Mark-Dey** [comment]
This is unrelated to the balance table, that has to do w/ zombie damage
